spring:
  application:
    name: openai
  profiles:
    active:  spy #, pgvector
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    openai:
      chat:
        options:
          functions:
            - weatherFunction
          n: 1
          model: "gpt-4o"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    openai:
      chat:
        base-url: "http://localhost:7777/openai"

---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/openai
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
