
spring:
  config:
    import: "optional:classpath:/creds.yaml"
  profiles:
    active: #pgvector
  ai:
    vectorstore:
      azure:
        initialize-schema: true
        index-name: spring-ai-document-index
    azure:
      openai:
        chat:
          options:
            functions:
              - weatherFunction
            temperature: 0.7
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        ai: DEBUG

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    azure:
      openai:
        endpoint: "http://localhost:7777/azure"
---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/azure
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
