spring:
  profiles:
    active: spy
  ai:
    ollama:
      base-url: "http://localhost:11434/"
      embedding:
        model: llama3
      chat:
        model: llama3

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    ollama:
      base-url: "http://localhost:7777/ollama"
