spring:
  profiles:
    active: # spy,pgvector
  ai:
    ollama:
      base-url: "http://localhost:11434/"
      embedding:        
        model: mxbai-embed-large
      chat:
        model: llama3.1
        # model: llava

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    ollama:
      base-url: "http://localhost:7777/ollama"

---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/ollama
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1024
