spring:
  profiles:
    active: # spy,pgvector
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    openai:
      chat:
        base-url: "https://api.openai.com/v1/chat/completions"
        options:
          functions:
            - weatherFunction
          n: 3
          model: "gpt-3.5-turbo"
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    openai:
      chat:
        base-url: "http://localhost:7777/openai"

---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/openai
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536