spring:
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    openai:
      chat:
        # comment / uncomment the lines below to switch between direct and indirect calls
        base-url: "https://api.openai.com/v1/chat/completions"
        # base-url: "http://localhost:7777/openai" # https://api.openai.com/v1/chat/completions
        options:
          functions:
            - weatherFunction
          n: 3
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

