# see
spring:
  ai:
    azure:
      openai:
        api-key:
        endpoint:
        chat:
          options:
            deployment-name: "gpt-35-turbo-16k"
            temperature: 0.7
    openai:
      api-key: