# copy and paste this file to be config/application.yaml and fill in your
# your api keys.
#
# see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files
#
spring:
  ai:
    azure:
      openai:
        api-key:
        endpoint:
        chat:
          options:
            deployment-name: "gpt-35-turbo-16k"
            temperature: 0.7
    openai:
      api-key: