spring:
  threads:
    virtual:
      enabled: true

server:
  port: 7777

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
