global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889']
