services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"   # OTLP gRPC receiver port
      - "4318:4318"   # OTLP HTTP receiver port
      - "9411:9411"   # Accept zipkin spans
    env_file:
      - .env
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command:
      - "--config=/etc/otel/config.yaml"

