receivers:
  zipkin:
    endpoint: "0.0.0.0:9411"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:8080']

processors:
  batch:

exporters:
  azuremonitor: {}

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [azuremonitor]

#receivers:
#  otlp:
#    protocols:
#      http:
#
#processors:
#  batch:
#
#exporters:
#  azuremonitor: {}
#
#service:
#  pipelines:
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [azuremonitor]
