global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['host.docker.internal:9090']

    - job_name: 'spring-ai-service'          
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production


    # - job_name: 'eureka'
    #   scheme: 'https'
      # eureka_sd_configs:
      #     - server: http://host.docker.internal:8761/eureka
      
    - job_name: 'tempo'
      static_configs:
        - targets: ['host.docker.internal:3200']
